# Generated by Django 5.2.7 on 2025-11-06 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='zip',
            field=models.IntegerField(default=000),
            preserve_default=False,
        ),
    ]
